name: Scraper

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Scraping website
      run: wget -r http://2020.csgames.org

    - name: Commiting changes
      run: git add . && git -c user.name='Github Actions' -c user.email='github@frigon.app' commit -am "$(date)"

    - name: Authenticating with the repository
      run: git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      
    - name: Updating the repository
      run: git push origin HEAD:${{ github.ref }}
    
    - name: Notify Slack Channel
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      run: |
        curl -X POST -d "{\"channel\":\"CMR0875M3\",\"text\":\"The CSGames :csgames: website was updated. See https://github.com/${{ github.repository }}/commit/$(git rev-parse HEAD)\"}" https://slack.com/api/chat.postMessage -H "Authorization: Bearer $SLACK_BOT_TOKEN" -H "Content-type: application/json"
